# Generated by Django 5.1.6 on 2025-04-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1234, max_length=100, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
