# Generated by Django 5.1.6 on 2025-06-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
