# Generated by Django 5.1.6 on 2025-06-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articles_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='user',
            new_name='user_id',
        ),
    ]
