# Generated by Django 5.1.6 on 2025-06-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_user_articles_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='user_id',
            new_name='user',
        ),
    ]
