# Generated by Django 5.1.6 on 2025-06-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.TextField(verbose_name='Дата публикации'),
        ),
    ]
