# Generated by Django 5.1.6 on 2025-06-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_articles_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.TextField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
