# Generated by Django 5.1.6 on 2025-06-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_rename_user_articles_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='articles',
            old_name='user_id',
            new_name='user',
        ),
    ]
