# Generated by Django 5.1.6 on 2025-06-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_rename_question_id_answers_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
